env:
  global:
    - secure: MVs4BixKLj/qTx2muyhXqLHPuHOl2dnJFxXwSNMrjWvLUEpNxQY3ug3pcklOc15Gd6gBqbsv2B4vysU0tDUGJYpx3rjYwwmA2wZNFuEbzxnIFyJej/9RwxZ3oK1E9iwDOr9RVPlDUOXrnz43CQ/kS/UdXtTr4xSFoVciUFMrzTv6szBdsUC24JG9Jh0T9dA6MXr2RsvXU2flvrL4KGJuIVXhtF0pLftJ21Bfv52aNxRLvMAfucGKh0Q7gf6Cm+HfixHat9dzbs1w56RSVLWBzu9OLZRqlBWe00dMeUG4V3QUxkqXisaEtftBJcri6K6bW/hCT82bC+NkkBa7fjiPz/u6e1k0woJFj0i/m4IK9HISCJv2g8ZFo2yArlyT5isNu2mwy6sZReNIbdRqUzvarawKjXIgTQK1n7L9isrq6kfvCHiDAUtqIBZKoA0+XsM+H1zlemZGzCo29vzdTdp2xoa98yjxa3hryNgMZCgEvC/ymZbtiHSVoBuykuNwvd1dWSJHTZcbTTigr3BnC5mWX6+Bm4L7mj3X/Kr488WVHdIHmHM1N0JJlYOFa5461HmR717Ke8nvZOrJcdN2zapQTA/u7TkmrbztvWx74pVlkTLl7zCF5myMG1PslKdUjFsmHXRp6GV/qUVT6cKvobESx2NjnvZqhjAhMO8yWHUF+Pk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/YousList
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
