env:
  global:
    - secure: y05DTsconuzPpQ/xebtZBndOn0fP25Ppw+1oxf8unvUOdfXx1BsSBVafPU6y63giDQW1a407OkT9KzisKbCfwdE6R6tO4rJ1hW4P1VuMLyf8EptbI51J1kf+44j/CyDyGOQCBccbIijgmx2wtZ4Pm3+4Xm1VT5I0UidkbVdjyOavGbVNOUhPvpJWo90p9sB57kBnU1v9POLL0nOVNdejQH7mJFvH1VpOAKInFE+WBAc+BGc+5O94qe1Gd94n/0zRz2j9EBvoz/okrP0aKnAtW1OOcZg0r9Z1IbaWWQaZ5L6H+X63AaUyRUeovH9BfRuJcD+TKjc4/rfGW757cP4dDQcM0DTW5mZtdPftxVReqpsif2fI/1CfViQtpO/uJXFRP+Un0bqsiOL6JYh0pdamyba9/bhG5XS4tUB6RgYu/tAQrLidxwUiI9B3prwNa/3p6xqVIXsJCL9Hh1K22Kw6p+51XEb3wga6/zZXv6TkPDfc0aics7+6KfEHJfkPF6QOK0G2imcZv0UQrxmdyMlc0jDZ7B4IMMVMla+Sl8QYE7TS8CGTowBmv7jZrLxlBktK4iZFGE/xJblg3BVTz/RkFYBnT5g7mlQ+vIdlK6OI+ca95zwoTOIi8xlOc/rqlicCz+dZW7fKSOpBjUqCAayr5858scCyJ8NoNRewWet5Fw0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/YousList
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
