env:
  global:
    - secure: Rmf3DFOlSdViaqyclGL483HaT/MOi3l+L0IBJo6RaX50NGbfxoeskccBFtgbJ4ZPufBNVU7xGO3oqY8jWNtah5cc0hfodpnmiRkElbwcj39stw70p/Si2XomLW4YInfuGx2A4YkU1hiAyKcWFL9USUJhb29Okm3NGimeOEiYrYWLZhDdQ+JzULQqKN0gqA6PCaVbGh7n95Kp2eVdhI4jBUBZGGKGhqsRklx0tHa+4E4TQybgSyys5ArYBHz0B41FNyf3La1jcN4VvnVULDmTQ2oomVO2sR0SXbvjlk3PPzZ+S1+U3ibaVikak33tA7r5OHmKgXsjdTYvxr03hPfyAiF07e0Perep+Q8x3j69+JgJXhQ+I+vpV5dC3yRBF7lRF5sA25/Tbzp0EUNgWREPyWFmUbMuK0hkSdOv1lXsq9ol5McLgb7EbFntB/GjWlMWTp0HVoESficXNzabRVJpQoiKlKDpAFeDN0zZXdFewZbn8KCoGWIfIBeO/SbRLzgOSBc4Og5zfcN5dFRFezJcAjyUHj8bRbpFMtTXezsz3jMChYgwkvfzqe9HV6slQJvcmFs+hTBTWL6WQId1tr4DvQNXKN9xORpXmGNfemlzzKRAYGYQ86HIaYMZyrtO38eqsiV2WcxZWsA3IAYgoog2cZIvnqNdf/pNMGafYgIeQjI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/YousList
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
