env:
  global:
    - secure: c+ahhKKBAMZuEPRrUgQ1GwNhZ1+sDQnnlosXwFSFJuj/FYH4uhFeCdZnUkqg0zQTh2i8v1e82y6O2eBkkJQM77gvajLOYNwVqxfbYlouDEGPySzjZbWm+IeG3bpMdjh5LKPA2oirzjgYYoCLiciu8fQN5pNT/k79s5bX2qnQjqE1hQCXGZpiY+c2/TCBgaKLGqKCn1tYfCd+8eF08cPQDb/qNmrRshxjTlr8b/uOxn+82EpbTqnkGTrGRY2PQtx0RqCLEz7q/J4VA1T7LonILEQSnVeHUcqqn3KOIPp3LlglOeDYwurfpWflRSpkL4bKWffojeWFoqTVERAgWBGyfLgr55mpwgEru73HZaxUazDvSibieiJFyD8JLynV3oRHI6sUygB2w50H4Wz6Vs/GGaUf1eFYYqGQyFzyAWVqpY8w/QfhejaFajEjMgYj8AM1v1XcC/mg0gZ8KPLVkbMdEAaaZNQNG+RTUE/775qwhskFeA6TCeuJK1FA+OWRjwLLOBt83guhG/95Niy2Oz8WByzFKZ4we6F4ozcVqpCKI3YfbgXeoPVB0jZlLsQPTFJsh9FzsqY2O/UQtLNVRXLgQaHTwDTqrzpgGfuJJXvB+bWfxIfcjIgQ+aVkaYrdw2CmO34KVnVwR+2QWk4d+4xQPdhoYMkBvTy6068Q8CadplA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/YousList
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
