env:
  global:
    - secure: yZIh12bb3n4GFkBedbrmHGzQzSZITOUgkaP1Q2euWQpUo+UzS1JKiy5dfBeuYIMBsQ9ETp4SeP8tBMnNqV0gFCDQep0Ag3ZO5/6RUZqwn9BHy7Du4AM4aI8A9dFvi605H0qJa58WRQibzp4d6ajbVVA6swF+wixocBVH1n/6nskbQhJ0WNPAmOUv8pjqZcNful+kTCzCicTPq8i0LodBWcysVVHTn+iPTUT5KoWdNfH8p8FyyH8Quf/2IPPFMSrrwh1dDr+ebMrw69/weNTF8f1fEJMW88QL1uqPUvzxkbEQ4NdZdaD/FObrgdVPal1+wLXt1C9n6hqaOxCFtS3OsoEJ2PbkdoeN7B0eSF2S4EAYouvkH+xPNSA+E+AekBvqhQPkZBvE5G/R2BXWWiMOzKawh/gN2m5fAZpv8GD2Dj0xqAsHx+Qv3e62rvEEPdTpGnCgfoLA0WWGrXQVXgk4MIhMBs1wZYxkETVZAXpVhv+yMiIrIv6K6Z1yi8oPq6e5HElJnhxx/J0BDsJgZ4iKDFNMWpXrWSrf1LKReeOaGFE2t0gnPG+aRwnBYLd6OgLJD3dhdyTVCrUFsif2l+F4hCgqj0dI6jQewFw2KK2RG1ewGjfBIqADCythhjBfOjPEahYE0BynaUoJhvbNmz5aP1K/ChZ5nvVNij9LpgawoNA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/YousList
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
